name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run unit tests against code
    runs-on: ubuntu-latest
    steps:
      - name: Install LLVM
        run: sudo apt-get install -y llvm-11
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup npm cache
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm config set cmake_LLVM_DIR=$(/usr/bin/llvm-config-11 --cmakedir)
          npm install
      - name: Test code changes
        run: npm test
  build:
    name: Build Node artifacts
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup npm cache
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build a lib and bin
        run: npm run build
  publish:
    name: Publish this npm project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup npm cache
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Publish pacakge
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN
          npm publish